### ISSUE TITLE
Add a working redux-thunk example

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/react-native-template#14]
In light of #13, seems like it would be worthwhile to have a working example that uses redux-thunk. Maybe a screen that pulls a quote from https://api.github.com/zen?

**Comment by purinkle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a working redux-thunk example](https://trello.com/c/FRLz35LX/13-add-a-working-redux-thunk-example)
