### ISSUE TITLE
Suppress GitHub diffs for generated files

### ISSUE THREAD

**Issue by croaky** [thoughtbot/react-native-template#25]
Thoughts on listing any generated files (android/buck/something?) to `.gitattributes` with `linguist-generated` attributes?

https://robots.thoughtbot.com/github-diff-supression

**Comment by purinkle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Suppress GitHub diffs for generated files](https://trello.com/c/M5ZhQr4B/16-suppress-github-diffs-for-generated-files)
