### ISSUE TITLE
Remove ESLint, rely entirely on Prettier?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/react-native-template#28]
I was hacking on a side project this weekend to learn RN. I created a repo directly from https://expo.io based on their tab navigation template (directly from their XDE desktop workflow). Then, I created an app from the thoughtbot template. I played with both for a while.

One thing I've been liking as a newcomer to RN is to simply have Prettier format the file on save. When I've tried to have ESLint w/ ALE in addition to Prettier on projects, it's been difficult to get both the ESLint rules and Prettier configured together so they don't clash.

While hacking, it's been much more pleasant to turn off editor linting entirely and just let Prettier format the file on save. Thoughts on dropping ESLint entirely for a similar flow here?

https://github.com/croaky/dotfiles/commit/e0cbf7852267e5044b6834f941c68896c89a90ef

**Comment by jakecraige** [comment]
I have yet to try Prettier yet but I'm pretty optimistic about it and would be interested in trying it on some projects. 

One of my concerns about it was lack of TypeScript support but it's looking like that may be working shortly https://github.com/prettier/prettier/issues/13 🎉

**Comment by croaky** [comment]
Nice, yeah, I've seen some TypeScript support being merged into Prettier recently (as recently as 5 minutes ago!). It's been a really nice experience, reminds me of working with Go.

Now there needs to be a tool like `goimports` for JavaScript! To automatically add and delete `import`s based on usage in the file... use `AsyncStorage` in the file? Save and `import { AsyncStorage } from "react-native";` could be added to the right spot in the fit.

**Comment by croaky** [comment]
Looks like the React team recommends Prettier over style guides: https://twitter.com/dan_abramov/status/871420769947049984

TypeScript and CSS support landed in Prettier 1.4 this week https://github.com/prettier/prettier/releases/tag/1.4.0

**Comment by jakecraige** [comment]
Badass. I set it up on my current client this week so I'll have a more thorough understanding and opinion on it shortly. So far so good (with Flow). I'll have to experiment with the TypeScript support in this project. Pretty exciting stuff though!

**Comment by purinkle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove ESLint, rely entirely on Prettier?](https://trello.com/c/qGYtWfQw/17-remove-eslint-rely-entirely-on-prettier)

**Comment by croaky** [comment]
Got a notification because I opened this. I've worked on a couple TypeScript React Native projects since then. The rough mix of tooling for linting has been:

`tsconfig.json`:

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "esModuleInterop": true,
    "jsx": "react",
    "lib": ["es2015", "es2016", "esnext"],
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "plugins": [
      {
        "configFile": "./tslint.json",
        "name": "typescript-tslint-plugin"
      }
    "strict": true,
    "target": "es5"
    ],
    "typeRoots": ["node_modules/@types"],
    "types": ["react", "react-native", "jest"]
  },
  "include": ["src/**/*"]
}
```

`tslint.json`:

```
{
  "defaultSeverity": "error",
  "extends": [
    "tslint:recommended",
    "tslint-config-prettier",
    "./tsconfig.json"
  ],
  "jsRules": {},
  "linterOptions": {
    "exclude": ["*.json", "**/*.json"]
  },
  "rules": {
    "interface-name": [false],
    "max-classes-per-file": [false],
    "member-ordering": false,
    "no-bitwise": false,
    "no-console": [false],
    "no-default-export": true,
    "no-unused-expression": {
      "options": ["allow-fast-null-checks"]
    },
    "no-var-requires": false,
    "object-literal-sort-keys": false,
    "one-variable-per-declaration": false,
    "ordered-imports": true,
    "trailing-comma": [
      true,
      {
        "multiline": {
          "typeLiterals": "never",
          "objects": "always",
          "arrays": "always"
        },
        "singleline": "never"
      }
    ],
    "semicolon": [true, "never"],
    "variable-name": [false]
  }
}
```

Some core `package.json` parts:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "android": "$(npm bin)/expo start --android",
    "eject": "$(npm bin)/expo eject",
    "ios": "$(npm bin)/expo start --ios",
    "start": "$(npm bin)/expo start"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "moment": "^2.24.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-navigation": "^3.3.0",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "styled-components": "^4.1.3"
  },
  "devDependencies": {
    "@types/expo": "^32.0.7",
    "@types/jest": "^24.0.11",
    "@types/react": "^16.7.6",
    "@types/react-native": "^0.57.11",
    "@types/react-navigation": "^3.0.3",
    "@types/react-redux": "7.0.1",
    "@types/react-test-renderer": "^16.8.1",
    "@types/redux-mock-store": "^1.0.0",
    "@types/styled-components": "^4.1.11",
    "babel-preset-expo": "^5.0.0",
    "expo-cli": "^2.13.0",
    "jest": "^24.6.0",
    "jest-expo": "^32.0.0",
    "prettier": "^1.15.2",
    "react-test-renderer": "^16.8.3",
    "redux-mock-store": "^1.5.3",
    "ts-jest": "^24.0.0",
    "tslint": "^5.11.0",
    "tslint-config-prettier": "^1.16.0",
    "typescript": "^3.1.6"
  },
  "private": true
}
```

Hope that's helpful!
