### ISSUE TITLE
Allowing a dash in company_name stops android build

### ISSUE THREAD

**Issue by benfurber** [thoughtbot/react-native-template#40]
When going through the `cookiecutter react-native-template` setup, the second option is company_name. I put in my name with a space. 

That space was changed to a dash for five locations where a package name is required, e.g.:
```
# /android/app/src/main/AndroidManifest.xml
...
      package="com.error-with-dash-name.appname">
...
```

This causes the android build to fail on `:app:processDebugResources`.

Removing the deadly dash enabled the build to run successfully.

**Comment by sharplet** [comment]
Looks like this might be the offending line: https://github.com/thoughtbot/react-native-template/blob/master/cookiecutter.json#L5

I wonder if using underscores would work?

**Comment by purinkle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allowing a dash in company_name stops android build](https://trello.com/c/gFWbCAgb/23-allowing-a-dash-in-companyname-stops-android-build)
