### ISSUE TITLE
Add React Native Debugger as the default debugger

### ISSUE THREAD

**Issue by purinkle** [thoughtbot/react-native-template#43]
We have started using React Native Debugger as the default debugger for our React Native projects. This should be reflected in our template.

**Comment by benfurber** [comment]
[Suggested implementation here](https://github.com/benfurber/ApprenticeProgress/commit/2b92e22e742574a0c78b309832bbe42ad9f96923).

**Comment by purinkle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add React Native Debugger as the default debugger](https://trello.com/c/3ZkeGix0/24-add-react-native-debugger-as-the-default-debugger)
