### ISSUE TITLE
Automatically regenerate cookiecutter and push to master with deploy hook

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/react-native-template#6]
Hat tip @gfontenot:

> what do you think about having the cookiecutter script run on CI as a deployment step and have it push a commit to master

This would absolve anyone of the responsibility of manually running `bin/generate` in their PR, and clean up diffs for code review.

**Comment by purinkle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automatically regenerate cookiecutter and push to master with deploy hook](https://trello.com/c/lVIXVxTy/11-automatically-regenerate-cookiecutter-and-push-to-master-with-deploy-hook)
